;;; Compiled snippets and support files for `markdown-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'markdown-mode
		     '(("pirate" "## Timeline\n* 12:01 `-` Negative note\n* 12:03 `+` Positive note\n* 12:06 Just a note!\n\n# Problem Navigation\n_Navigates issues in the development space_\n_Focuses on important problem areas and guides parts of the interview_\n_Organizes, structures, and/or analyzes the problem space_\n\n# Solution Design\n_Creates a working solution that addresses key aspects of the problem/design_\n_Accounts for scalability to large quantities of users and data_\n_Designs with user experience and problem in mind_\n_Deploys architectural/design patterns with extensibility and multiple developers in mind_\n\n# Technical Communication\n_Communicates technical concepts in a focused and logical manner_\n_Articulates technical ideas and trade-offs_\n_Engages with technical queries and feedback from the interviewer_\n\n# Technical Excellence\n_Demonstrates technical knowledge of concepts/techniques/frameworks/APIs_\n_Dives into technical details where appropriate_\n_Articulates multiple options and assesses trade-offs_\n_Foresees potential points of failure_\n" "pirate" nil nil nil "/Users/gauglertodd/.emacs.d/snippets/markdown-mode/pirate" nil nil)
		       ("mlpirate" "# Focus Area: Problem Navigation\n## Navigates issues in the development space\n## Focuses on important problem areas and guides parts of the interview*\n## Organizes, structures, and/or analyzes the problem space*\n\n# Focus Area: Training Data\n## Considers how to acquire and label the data as appropriate\n## Chooses and justifies appropriate data solutions for the given task\n## Provides implementation details for the collection of training data\n\n# Focus Area: Feature Engineering\n## Identifies a comprehensive set of implementable and problem-appropriate features\n## Organizes, structures, and prioritizes the signals\n## Considers the end-to-end use of features in the modeling solution\n\n# Focus Area: Modeling\n## Demonstrates familiarity with relevant modeling techniques\n## Discusses technical implementation details\n## Identifies root causes and solves issues with model training\n\n# Focus Area: Evaluation & Deployment\n## Considers the deployment and evaluation strategy\n" "mlpirate" nil nil nil "/Users/gauglertodd/.emacs.d/snippets/markdown-mode/mlpirate" nil nil)
		       ("mlinfra" "# Problem Exploration\n# Modeling Approaches\n# Infrastructure Design\n# Storage / Logging\n# Training / Testing\n# Deployment\n" "mlinfra" nil nil nil "/Users/gauglertodd/.emacs.d/snippets/markdown-mode/mlinfra" nil nil)))


;;; Do not edit! File generated at Mon Sep 26 15:58:34 2022
